### ISSUE TITLE
Publish 0.11.0 on apm

### ISSUE THREAD

**Issue by caleb531** [lalyos/ssh-config#9]
Hi @lalyos. Back in https://github.com/lalyos/ssh-config/commit/1f59a29aa8efba78808da99d64d867c7383049eb a few months ago, you released 0.11.0 of ssh-config. However, the latest version on apm is still 0.10.1. Could you please publish v0.11.0 to apm so we can all benefit from the most recent changes?

Thanks,
Caleb

**Comment by lalyos** [comment]
done
```
Preparing and tagging a new version ✓
Pushing v0.12.0 tag ✓
Publishing ssh-config@v0.12.0 ✓
```
